version: '3.8' 

services:
  pupil_dev:
    build:
      context: .
      dockerfile: Dockerfile.pupil_dev
      args:
          USER_ID: ${UID:-1000}
          GROUP_ID: ${GID:-1000}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ./app/pupil_capture_settings:/app/pupil/capture_settings
    devices:
      - /dev/video0:/dev/video0
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
    network_mode: host
    privileged: true
    group_add:
      - plugdev
    command: "bin/bash" # Start the container with bash
